### ISSUE TITLE
How to use the twig-stack-exension with Timber - gutenberg?

### ISSUE THREAD

**Issue by merijnponzo** [filhocodes/twig-stack-extension#1]
Hello,

I tested the twig-stack-extension and it's working with Wordpress Timber/Twig but not with the advanced custom fields - gutenberg blocks.

My guess is that your code is not seeing that Timber::render is parsing the blocks/content, since it only works with include. embed or extends. 

I also posted the issue on timber but I hoped putting some energy together will find a solution
https://github.com/timber/timber/issues/2489

It would be awesome if we could stack the code from within the gutenberg blocks as well

**Comment by filhocodes** [comment]
If you can confirm:

Timber is creating a new `TwigEnvironment` for each call of `Loader::render()`
https://github.com/timber/timber/blob/e339378d81578c5587dc5c11a1f7d44c5fa29792/lib/Loader.php#L158-L198
https://github.com/timber/timber/blob/e339378d81578c5587dc5c11a1f7d44c5fa29792/lib/Loader.php#L70

And it is creating a new `Loader` for each call of `Timber::compile()`, which is called by `Timber::render()`
https://github.com/timber/timber/blob/e339378d81578c5587dc5c11a1f7d44c5fa29792/lib/Loader.php#L70

Since `StacksManager` is not a static/global class, what is happening is that the contents of your push and prepend nodes are being held only for that `Timber::render()` execution.

**Comment by merijnponzo** [comment]
Thanks @filhocodes , I cross-posted your comment to the discussion i already with Jared Nova (maker of timber) started on timber.

I hope there is something possible with these to awesome repo's to push out all of the javascript  from the gutenberg twig blocks to the footer ;-) !

**Comment by filhocodes** [comment]
I am closing this issue due to the following:

I don't really want to implement an optional static version of `TwigStackExtension` that would share the stacks across any Twig Environment because it's not a behavior that I would want to promote. It could open to a bad developer experience about managing which stacks should be shared between environment, and which ones should not.

I am open to change this idea if it's really a needed feature, but as it stands, it's more a conflict with Timber implementation.
